const pathRoutesPage = {
  Login: "/login",
  ApplicationDownload: "/application_download",
  Dashboard: "/dashboard",
  // Home: "/home",
  HomeCate: "/homeCate",
  HomeType: "/homeType",
  Items: "/items",
  CategoryItem: "/category_item",
  TypeItems: "/typeItem_item",
  Faculty: "/faculty",
  Department: "/department",
  Building: "/building",
  Location: "/location",
  TypeItemSetting: "/type_item",
  CategorySetting: "/category",
  NewItem: "/newitem",
  NewFaculty: "/newfaculty",
  NewDepartment: "/newdepartment",
  NewBuilding: "/newbuilding",
  NewLocation: "/newlocation",
  NewTypeItem: "/newTypeItem",
  NewCateItem: "/newCategory",
  //
  EditItem: "/items/editItem",
  EditFaculty: "/faculty/editfaculty",
  EditDepartment: "/departmen/editdepartmen",
  EditBuilding: "/building/editbuilding",
  EditLocation: "/location/editlocation",
  EditCategory: "/category/editCategory",
  EditTypeItem: "/type_item/editTypeItem",
  EditUser: "/admin/editUser",
  Profile: "/profile",
  Users: "/admin",
  NewUser: "/admin/new_user",
};

export default pathRoutesPage;
