const pathRoutesPage = {
  Login: "/login",
  ApplicationDownload: "/application_download",
  Dashboard: "/dashboard",
  // Home: "/home",
  HomeCate: "/homeCate",
  HomeType: "/homeType",
  Items: "/items",
  CategoryItem: "/category_item",
  TypeItems: "/typeItem_item",
  Faculty: "/faculty",
  Department: "/department",
  Building: "/building",
  Location: "/location",
  TypeItemSetting: "/type_item",
  CategorySetting: "/category",
  NewItem: "/newitem",
  NewFaculty: "/newfaculty",
  NewDepartment: "/newdepartment",
  NewBuilding: "/newbuilding",
  NewLocation: "/newlocation",
  NewTypeItem: "/newTypeItem",
  NewCateItem: "/newCategory",
  //
  EditItem: "/editItem",
  EditFaculty: "/editfaculty",
  EditDepartment: "/editdepartmen",
  EditBuilding: "/editbuilding",
  EditLocation: "/editlocation",
  EditCategory: "/editCategory",
  EditTypeItem: "/editTypeItem",
  EditUser: "/editUser",
  // 
  Profile: "/profile",
  Users: "/admin",
  NewUser: "/new_user",
};

export default pathRoutesPage;
