const testData = [
  {
    id: "1",
    code: "1234",
    faculty: "dasdasd",
    department: "asdasdasd",
    building: "adwdadad",
    location: "3/4asdadwdzcsad",
    cost: "3500",
    item_status: "Normal",
    creator: "Admin",
    created_at: "3/3/3",
  },
  {
    id: "2",
    code: "1234",
    faculty: "dasdasd",
    department: "asdasdasd",
    building: "adwdadad",
    location: "3/4asdadwdzcsad",
    cost: "3500",
    item_status: "Normal",
    creator: "Admin",
    created_at: "3/3/3",
  },
  {
    id: "3",
    code: "1234",
    faculty: "dasdasd",
    department: "asdasdasd",
    building: "adwdadad",
    location: "3/4asdadwdzcsad",
    cost: "3500",
    item_status: "Normal",
    creator: "Admin",
    created_at: "3/3/3",
  },
  {
    id: "4",
    code: "1234",
    faculty: "dasdasd",
    department: "asdasdasd",
    building: "adwdadad",
    location: "3/4asdadwdzcsad",
    cost: "3500",
    item_status: "Normal",
    creator: "Admin",
    created_at: "3/3/3",
  },
];

export default testData;
