export const testDataLocation = [
  {
    id: "1",
    code: "1234",
    NameTH: "วิศวไฟฟ้า",
    NameEN: "	power elec",
    Faculty: "คณะวิศวกรรมศาสตร์",
    Department: "วิศวกรรมไฟฟ้า",
    Building: "อาคาร2",
    Floor: "7",
  },
  {
    id: "2",
    code: "1234",
    NameTH: "ห้องคอม",
    NameEN: "com",
    Faculty: "คณะวิศวกรรมศาสตร์",
    Department: "วิศวกรรมคอม",
    Building: "อาคาร3",
    Floor: "3",
  },
  {
    id: "3",
    code: "1234",
    NameTH: "อาคาร50ปี",
    NameEN: "50years",
    Faculty: "คณะวิศวกรรมศาสตร์",
    Department: "คณะวิศวกรรมศาสตร์",
    Building: "อาคาร18",
    Floor: "2",
  },
  {
    id: "4",
    code: "1234",
    NameTH: "วิจัยณัฎฐกา",
    NameEN: "project",
    Faculty: "คณะแพทยศาสตร์",
    Department: "คณะแพทยศาสตร์",
    Building: "อาคาร15",
    Floor: "2",
  },
];

export const thLocation = [
  "ลำดับ",
  "Edit",
  "Code",
  "Name TH",
  "Name EN",
  "Faculty",
  "Department",
  "Building",
  "Floor",
];
